module.exports = {
  concepts: [{type: 'autogenerated', dirName: 'concepts'}],
  developers: [
    'developers/intro',
    { type: 'category', label: 'Identity API', items: [{ type: 'autogenerated', dirName: 'developers/api' }] },
    { type: 'category', label: 'Identity SDK', items: [{ type: 'autogenerated', dirName: 'developers/sdk' }] },
  ],
  about: [{ type: 'autogenerated', dirName: 'about' }],
};
